apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-cert
spec:
  secretName: jellyfin-tls-secret
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.lan
