apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-config
spec:
  storageClassName: local-path
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jellyfin/app"
  claimRef:
    namespace: jellyfin
    name: jellyfin-config-pvc