apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr-cert
spec:
  secretName: homarr-tls-secret
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - homarr.lan