apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls-secret
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - keycloak.lan