fullnameOverride: external-dns-pihole
logLevel: &logLevel debug
provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/tarantini-io/external-dns-pihole-webhook
      tag: v1.0.0 # or specific tag
    env:
      - name: PIHOLE_SERVER
        value: http://pihole.lan
      - name: PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
      - name: LOG_LEVEL
        value: *logLevel
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
policy: sync
sources: ["ingress", "service"] # or whatever you need
txtOwnerId: ""
txtPrefix: ""
domainFilters: [".lan", "lan"] # your domain