apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder
spec:
  instances: 1
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-db-password
  storage:
    storageClass: nfs-truenas-retain
    size: 10Gi
