apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus-cert
spec:
  secretName: gatus-tls-secret
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - gatus.lan