apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: gatus
data:
  config.yaml: |
    alerting:
      ntfy:
        topic: "Gatus"
        url: "https://ntfy.cjhome.uk"
        token: "tk_rqc4vzwto7lwbamplehjccxwnbfiq"
        click: https://gatus.lan
        default-alert:
          send-on-resolved: true
          failure-threshold: 2
          success-threshold: 2

    metrics: true

    default-endpoint: &local
      group: local
      interval: 1m
      client:
        insecure: true
        timeout: 30s
      conditions:
        - "[STATUS] == any(200, 403)"
      alerts:
        - type: ntfy
    
    default-endpoint-public: &public
      group: public
      interval: 1m
      client:
        timeout: 30s
      conditions:
        - "[STATUS] == any(200, 403)"
      alerts:
        - type: ntfy

    endpoints:
      - name: Immich
        url: https://immich.cjhome.uk
        <<: *public
        group: public

      - name: Vault Warden
        url: https://vw.cjhome.uk
        <<: *public
        group: public

      - name: OpenWeb UI
        url: https://ai.cjhome.uk
        <<: *public
        group: public

      - name: Keycloak
        url: https://keycloak.cjhome.uk
        <<: *public
        group: public

      - name: Jellyfin
        url: https://jellyfin.cjhome.uk
        <<: *public
        group: public

      - name: Unifi
        url: https://unifi.lan
        <<: *local

      - name: Pihole
        url: http://pihole.lan/admin
        <<: *local
      
      - name: Synology Nas
        url: https://nas.lan
        <<: *local
      
      - name: Proxmox
        url: https://proxmox.lan:8006
        <<: *local
      
      - name: Jellyfin
        url: https://jellyfin.lan
        <<: *local
      
      - name: QBitorrent
        url: https://qbit.lan
        <<: *local
      
      - name: Tiny Media Manager
        url: https://tmm.lan
        <<: *local
      
      - name: Vault Warden
        url: https://vw.lan
        <<: *local

      - name: Harbor
        url: https://harbor.lan
        <<: *local

      - name: FreshRSS
        url: https://freshrss.lan
        <<: *local

      - name: Home Assistant
        url: http://hass.lan:8123
        <<: *local
      
      - name: Spotify Cleaner
        url: https://sp.lan
        <<: *local
      
      - name: Coder
        url: https://coder.lan:8006
        <<: *local
      
      - name: OpenWeb UI
        url: https://ai.lan
        <<: *local
      
      - name: Jellyseerr
        url: https://jellyseerr.lan
        <<: *local
      
      - name: Radarr
        url: https://radarr.lan
        <<: *local
      
      - name: Sonarr
        url: https://sonarr.lan
        <<: *local

      - name: Prowlarr
        url: https://prowlarr.lan
        <<: *local

      - name: Argo CD
        url: https://argocd.lan
        <<: *local

      - name: Vault
        url: https://vault.lan
        <<: *local
      
      - name: Immich
        url: https://immich.lan
        <<: *local

      - name: Jenkins
        url: https://jenkins.lan
        <<: *local

      - name: Navidrome
        url: https://music.lan
        <<: *local