apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-cert
  namespace: litellm
spec:
  secretName: litellm-tls-secret
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - litellm.lan