apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm
spec:
  instances: 1
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: litellm-db-password
  storage:
    storageClass: nfs
    size: 20Gi
