apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:v1.77.3-stable
        # args:
          # - "--config"
          # - "/app/proxy_server_config.yaml"
        ports:
        - containerPort: 4000
        # volumeMounts:
        # - name: config-volume
        #   mountPath: /app/proxy_server_config.yaml
        #   subPath: config.yaml
        env: 
          - name: LITELLM_MASTER_KEY
            value: ###ZARF_VAR_LITELLM_MASTER_KEY###
          - name: LITELLM_SALT_KEY
            value: ###ZARF_VAR_LITELLM_SALT_KEY###
          - name: STORE_MODEL_IN_DB
            value: "true"
        envFrom:
        - secretRef:
            name: litellm-db-password
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: litellm-config-file